### ISSUE TITLE
React 18 Question

### ISSUE THREAD

**Issue by gmonk** [nomcopter/react-mosaic#188] opened 2022-06-09 22:47 UTC
Trying to use reac-mosaic with React 18 and getting the following errors

Could not find the drag and drop manager in the context of DragSource(InternalMosaicWindow2). Make sure to render a DndProvider component in your top-level component

Does this support later versions of react ?

**Comment by nomcopter** [comment] 2022-06-30 01:02
Duplicate of https://github.com/nomcopter/react-mosaic/issues/175

**Closed by nomcopter** 2022-06-30 01:02 UTC
